name: check
on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3.4.0
      - name: Install Dependencies
        run: scripts/setup/all.sh
      - name: Build documentation
        run: scripts/mkdocs/build.sh
      - name: Run Linters
        run: scripts/linting/all.sh
