name: ci
on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: scripts/setup/all.sh
      - run: scripts/mkdocs/build.sh
      - run: scripts/linting/all.sh
      - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: scripts/mkdocs/deploy.sh
